<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "spt_socialmedia"
 *
 * Auto generated by Extension Builder 2017-12-09
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Social Media Widget',
    'description' => 'Extension to manage social media widgets.',
    'category' => 'plugin',
    'author' => 'Arun Chandran',
    'author_email' => 'arun@spawoz.com',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '4.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '11.0.0-11.99.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
